version: 2
updates:
  # Update yarn dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      next:
        patterns:
          - "next"
          - "@next/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    
  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5 