apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: qbit
  labels:
    app: qbit
    service: auth
type: Opaque
# The values below need to be base64 encoded for production use.
# You can encode values using: echo -n 'your-secret' | base64
# For development purposes, you can use stringData instead of data to avoid base64 encoding
stringData:
  # Authentication secrets
  JWT_SECRET: "jwt_secret_key_replace_in_production"
  JWT_REFRESH_SECRET: "jwt_refresh_secret_key_replace_in_production"
  SERVICE_JWT_SECRET: "service_jwt_secret_key_replace_in_production"
  
  # Database credentials
  DATABASE_PASSWORD: "auth_db_password_replace_in_production"
  
  # External service credentials
  RABBITMQ_PASSWORD: "rabbitmq_password_replace_in_production"
  
  # Cookie settings
  COOKIE_SECRET: "cookie_secret_key_replace_in_production"
  
  # CSRF protection
  CSRF_SECRET: "csrf_secret_key_replace_in_production" 