apiVersion: v1
kind: Secret
metadata:
  name: general-ledger-secrets
  namespace: qbit
  labels:
    app: qbit
    service: general-ledger
type: Opaque
# The values below need to be base64 encoded for production use.
# You can encode values using: echo -n 'your-secret' | base64
# For development purposes, you can use stringData instead of data to avoid base64 encoding
stringData:
  # Service authentication
  SERVICE_JWT_SECRET: "service_jwt_secret_key_replace_in_production"
  SERVICE_TOKEN: "gl_service_token_replace_in_production"
  
  # Database credentials
  DATABASE_PASSWORD: "gl_db_password_replace_in_production"
  
  # External service connections
  AUTH_SERVICE_URL: "http://auth-service:3002"
  
  # Message broker credentials
  RABBITMQ_PASSWORD: "rabbitmq_password_replace_in_production"
  
  # Financial data processing
  ENCRYPTION_KEY: "financial_data_encryption_key_replace_in_production"
  
  # Audit logging
  AUDIT_LOG_SECRET: "audit_log_secret_key_replace_in_production"
  
  # Integration with tax calculation service
  TAX_SERVICE_API_KEY: "tax_service_api_key_replace_in_production" 