apiVersion: apps/v1
kind: Deployment
metadata:
  name: general-ledger-deployment
  labels:
    app: general-ledger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: general-ledger
  template:
    metadata:
      labels:
        app: general-ledger
    spec:
      containers:
      - name: general-ledger
        image: ${DOCKER_REGISTRY}/qbit-general-ledger:latest
        ports:
        - containerPort: 3003
        envFrom:
        - configMapRef:
            name: general-ledger-config
        - secretRef:
            name: general-ledger-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: general-ledger-service
spec:
  selector:
    app: general-ledger
  ports:
  - port: 3003
    targetPort: 3003
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: general-ledger-config
data:
  NODE_ENV: "production"
  PORT: "3003"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "qbit_general_ledger"
  DATABASE_USER: "postgres"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "qbit"
  CONSUL_HOST: "consul-service"
  CONSUL_PORT: "8500"
  SERVICE_NAME: "general-ledger-service" 