apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: ${DOCKER_REGISTRY}/qbit-inventory:latest
        ports:
        - containerPort: 3008
        envFrom:
        - configMapRef:
            name: inventory-config
        - secretRef:
            name: inventory-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3008
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3008
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory
  ports:
  - port: 3008
    targetPort: 3008
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  NODE_ENV: "production"
  PORT: "3008"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "inventory"
  DATABASE_USER: "postgres"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "qbit"
  CONSUL_HOST: "consul-service"
  CONSUL_PORT: "8500"
  SERVICE_NAME: "inventory-service"
  AUTH_SERVICE_URL: "http://auth-service:3002"
  GENERAL_LEDGER_SERVICE_URL: "http://general-ledger-service:3003" 