// Export common icons used in the application from lucide-react

import {
  Trash2,
  Plus,
  Calendar,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  X,
  Check,
  CreditCard,
  User,
  Settings,
  LogOut,
  Edit,
  Search,
  Filter,
  Download,
  Upload,
  FileText,
  AlertTriangle,
  ExternalLink,
  RefreshCw,
  ArrowRight,
  ArrowLeft,
  ArrowRightLeft,
  Package,
  XCircle,
  Menu,
  BarChart,
  Home,
  DollarSign,
  Users,
  Archive,
  Printer
} from "lucide-react";

export { 
  Trash2 as TrashIcon,
  Plus as PlusIcon,
  Calendar as CalendarIcon,
  MoreVertical as MoreVerticalIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  X as XIcon,
  Check as CheckIcon,
  CreditCard as CreditCardIcon,
  User as UserIcon,
  Settings as SettingsIcon,
  LogOut as LogOutIcon,
  Edit as EditIcon,
  Search as SearchIcon,
  Filter as FilterIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  FileText as FileTextIcon,
  AlertTriangle as AlertTriangleIcon,
  ExternalLink as ExternalLinkIcon,
  RefreshCw as RefreshCwIcon,
  ArrowRight as ArrowRightIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRightLeft as ArrowRightLeftIcon,
  Package as PackageIcon,
  XCircle as XCircleIcon,
  Menu as MenuIcon,
  BarChart as BarChartIcon,
  Home as HomeIcon,
  DollarSign as DollarSignIcon,
  Users as UsersIcon,
  Archive as ArchiveIcon,
  Printer as PrintIcon
};

// Add a spinning icon based on RefreshCw
export const SpinnerIcon = (props: React.ComponentProps<typeof RefreshCw>) => (
  <RefreshCw {...props} className={`animate-spin ${props.className || ''}`} />
); 