apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: qbit
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbit-secrets
  namespace: qbit
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    creationPolicy: Owner
  data:
    # PostgreSQL secrets
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: qbit/database
        property: postgres-password
    
    # JWT secrets
    - secretKey: JWT_SECRET
      remoteRef:
        key: qbit/auth
        property: jwt-secret
    - secretKey: SERVICE_JWT_SECRET
      remoteRef:
        key: qbit/auth
        property: service-jwt-secret
    
    # RabbitMQ secrets
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: qbit/messaging
        property: rabbitmq-password
---
# Template to generate individual service secrets from the main external secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: qbit
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: qbit/auth
        property: jwt-secret
    - secretKey: SERVICE_JWT_SECRET
      remoteRef:
        key: qbit/auth
        property: service-jwt-secret
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: qbit/messaging
        property: rabbitmq-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: qbit
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: qbit/auth
        property: jwt-secret
    - secretKey: SERVICE_JWT_SECRET
      remoteRef:
        key: qbit/auth
        property: service-jwt-secret
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: qbit/database
        property: postgres-password
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: qbit/messaging
        property: rabbitmq-password 