apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: client
  - name: monitoring
    port: 8222
    targetPort: monitoring
  type: ClusterIP 