apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: qbit
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ${DOCKER_REGISTRY}/qbit-auth:latest
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: auth-service-config
        - secretRef:
            name: auth-service-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: qbit
spec:
  selector:
    app: auth-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: qbit
data:
  NODE_ENV: "production"
  PORT: "3002"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "qbit_auth"
  SERVICE_NAME: "auth-service"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  CONSUL_HOST: "consul-service"
  CONSUL_PORT: "8500" 