name: 'Setup Docker'
description: 'Sets up Docker Buildx and logs in to Docker Hub'

inputs:
  docker-username:
    description: 'Docker Hub username'
    required: true
  docker-token:
    description: 'Docker Hub token'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-token }}
        
    - name: Docker info
      shell: bash
      run: docker info 