http.host: "0.0.0.0"
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["${ELASTICSEARCH_URL}"]
path.config: /usr/share/logstash/pipeline
config.reload.automatic: true
config.reload.interval: 30s
log.level: info
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50
queue.type: memory 