export enum AccountType {
  ASSET = 'ASSET',
  LIABILITY = 'LIABILITY',
  EQUITY = 'EQUITY',
  REVENUE = 'REVENUE',
  EXPENSE = 'EXPENSE'
}

export enum AccountSubType {
  CASH = 'CASH',
  ACCOUNTS_RECEIVABLE = 'ACCOUNTS_RECEIVABLE',
  INVENTORY = 'INVENTORY',
  FIXED_ASSETS = 'FIXED_ASSETS',
  ACCOUNTS_PAYABLE = 'ACCOUNTS_PAYABLE',
  LOANS = 'LOANS',
  CAPITAL = 'CAPITAL',
  RETAINED_EARNINGS = 'RETAINED_EARNINGS',
  SALES = 'SALES',
  OTHER_INCOME = 'OTHER_INCOME',
  COST_OF_GOODS_SOLD = 'COST_OF_GOODS_SOLD',
  OPERATING_EXPENSES = 'OPERATING_EXPENSES',
  TAXES = 'TAXES',
  OTHER_EXPENSE = 'OTHER_EXPENSE'
} 