name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/dependabot.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Enable Corepack and Install Correct Yarn
        run: |
            corepack enable
            corepack prepare yarn@3.7.0 --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build packages
        run: yarn build
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      # Core services
      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./services/api-gateway
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-api-gateway:latest
      
      - name: Build and push Auth Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-auth:latest
      
      # Financial services
      - name: Build and push General Ledger Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/general-ledger
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-general-ledger:latest
      
      - name: Build and push Accounts Payable Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/accounts-payable
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-accounts-payable:latest
      
      - name: Build and push Accounts Receivable Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/accounts-receivable
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-accounts-receivable:latest
      
      - name: Build and push Banking Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/banking
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-banking:latest
      
      - name: Build and push Fixed Assets Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/fixed-assets
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-fixed-assets:latest
      
      - name: Build and push Inventory Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/inventory
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-inventory:latest
      
      - name: Build and push Reporting Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/reporting
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-reporting:latest
      
      # Frontend
      - name: Build and push Web App
        uses: docker/build-push-action@v4
        with:
          context: ./apps/web
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-web:latest

  migrate-databases:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Install database migration dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run database status check
        run: |
          echo "Checking database status before migrations..."
          
          # Auth service
          echo "Auth Service:"
          DATABASE_URL=${{ secrets.AUTH_DB_URL }} yarn workspace auth prisma migrate status

          # General Ledger
          echo "General Ledger:"
          DATABASE_URL=${{ secrets.GL_DB_URL }} yarn workspace general-ledger prisma migrate status
          
          # Accounts Payable
          echo "Accounts Payable:"
          DATABASE_URL=${{ secrets.AP_DB_URL }} yarn workspace accounts-payable prisma migrate status
          
          # Accounts Receivable
          echo "Accounts Receivable:"
          DATABASE_URL=${{ secrets.AR_DB_URL }} yarn workspace accounts-receivable prisma migrate status
          
          # Banking
          echo "Banking:"
          DATABASE_URL=${{ secrets.BANKING_DB_URL }} yarn workspace banking prisma migrate status
          
          # Fixed Assets
          echo "Fixed Assets:"
          DATABASE_URL=${{ secrets.FA_DB_URL }} yarn workspace fixed-assets prisma migrate status
          
          # Inventory
          echo "Inventory:"
          DATABASE_URL=${{ secrets.INVENTORY_DB_URL }} yarn workspace inventory prisma migrate status
          
          # Reporting
          echo "Reporting:"
          DATABASE_URL=${{ secrets.REPORTING_DB_URL }} yarn workspace reporting prisma migrate status
      
      - name: Run database migrations
        id: run-migrations
        run: |
          echo "Running database migrations..."
          
          # Auth service migrations
          echo "Migrating Auth Service..."
          DATABASE_URL=${{ secrets.AUTH_DB_URL }} yarn workspace auth prisma migrate deploy
          
          # General Ledger migrations
          echo "Migrating General Ledger..."
          DATABASE_URL=${{ secrets.GL_DB_URL }} yarn workspace general-ledger prisma migrate deploy
          
          # Accounts Payable migrations
          echo "Migrating Accounts Payable..."
          DATABASE_URL=${{ secrets.AP_DB_URL }} yarn workspace accounts-payable prisma migrate deploy
          
          # Accounts Receivable migrations
          echo "Migrating Accounts Receivable..."
          DATABASE_URL=${{ secrets.AR_DB_URL }} yarn workspace accounts-receivable prisma migrate deploy
          
          # Banking migrations
          echo "Migrating Banking..."
          DATABASE_URL=${{ secrets.BANKING_DB_URL }} yarn workspace banking prisma migrate deploy
          
          # Fixed Assets migrations
          echo "Migrating Fixed Assets..."
          DATABASE_URL=${{ secrets.FA_DB_URL }} yarn workspace fixed-assets prisma migrate deploy
          
          # Inventory migrations
          echo "Migrating Inventory..."
          DATABASE_URL=${{ secrets.INVENTORY_DB_URL }} yarn workspace inventory prisma migrate deploy
          
          # Reporting migrations
          echo "Migrating Reporting..."
          DATABASE_URL=${{ secrets.REPORTING_DB_URL }} yarn workspace reporting prisma migrate deploy
      
      - name: Run database seed (only on initial setup)
        if: github.event.inputs.seed == 'true'
        run: |
          echo "Running database seeds..."
          DATABASE_URL=${{ secrets.AUTH_DB_URL }} yarn workspace auth prisma db seed
          echo "Seeds completed."
          
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs: migrate-databases
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
      
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      
      # Install and set up Kustomize
      - name: Set up Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
      
      # Secrets Management (still needed for databases, etc. that don't use Kustomize)
      - name: Create Kubernetes secrets
        run: |
          echo "Creating Kubernetes secrets from GitHub secrets..."
          
          # Create namespace if not exists
          kubectl create namespace qbit --dry-run=client -o yaml | kubectl apply -f -
          
          # Create PostgreSQL password secret
          kubectl create secret generic postgres-secrets \
            --from-literal=POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' \
            --namespace qbit \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Create RabbitMQ secrets
          kubectl create secret generic rabbitmq-secrets \
            --from-literal=RABBITMQ_PASSWORD='${{ secrets.RABBITMQ_PASSWORD }}' \
            --namespace qbit \
            --dry-run=client -o yaml | kubectl apply -f -
      
      # Update secrets in environment files
      - name: Update production secrets in environment files
        run: |
          # Update database secrets
          sed -i 's/password/${{ secrets.POSTGRES_PASSWORD }}/g' k8s/overlays/production/database-secrets.env
          
          # Update auth secrets
          sed -i 's/your-production-jwt-secret-here/${{ secrets.JWT_SECRET }}/g' k8s/overlays/production/auth-secrets.env
          sed -i 's/your-production-refresh-token-secret-here/${{ secrets.REFRESH_TOKEN_SECRET }}/g' k8s/overlays/production/auth-secrets.env
          
          # Update general ledger secrets
          sed -i 's/password/${{ secrets.POSTGRES_PASSWORD }}/g' k8s/overlays/production/general-ledger-secrets.env
          sed -i 's/your-production-gl-api-key-here/${{ secrets.GL_API_KEY }}/g' k8s/overlays/production/general-ledger-secrets.env
          
          # Update accounts payable secrets
          sed -i 's/password/${{ secrets.POSTGRES_PASSWORD }}/g' k8s/overlays/production/accounts-payable-secrets.env
          sed -i 's/your-production-ap-api-key-here/${{ secrets.AP_API_KEY }}/g' k8s/overlays/production/accounts-payable-secrets.env
          
          # Update accounts receivable secrets
          sed -i 's/password/${{ secrets.POSTGRES_PASSWORD }}/g' k8s/overlays/production/accounts-receivable-secrets.env
          sed -i 's/your-production-ar-api-key-here/${{ secrets.AR_API_KEY }}/g' k8s/overlays/production/accounts-receivable-secrets.env
          
          # Update inventory secrets
          sed -i 's/password/${{ secrets.POSTGRES_PASSWORD }}/g' k8s/overlays/production/inventory-secrets.env
          sed -i 's/your-production-inventory-api-key-here/${{ secrets.INVENTORY_API_KEY }}/g' k8s/overlays/production/inventory-secrets.env
      
      # Apply infrastructure first
      - name: Deploy Core Infrastructure with Kustomize
        run: |
          # Apply the database, Redis, and RabbitMQ separately first
          kubectl apply -f k8s/database.yaml -n qbit
          kubectl apply -f k8s/redis.yaml -n qbit
          kubectl apply -f k8s/rabbitmq.yaml -n qbit
          
          # Wait for infrastructure to be ready
          kubectl wait --for=condition=available deployment/redis --timeout=300s -n qbit
          kubectl wait --for=condition=ready pod -l app=postgres --timeout=300s -n qbit
      
      # Deploy using Kustomize
      - name: Deploy to Production with Kustomize
        run: |
          # Deploy using kustomize
          kustomize build k8s/overlays/production | kubectl apply -f -
          
          # Check deployment status
          kubectl get deployment -n qbit
      
      # Post-deployment validation
      - name: Validate deployments
        run: |
          echo "Validating deployments..."
          kubectl get deployments -n qbit
          kubectl wait --for=condition=available deployment/api-gateway --timeout=300s -n qbit
          kubectl wait --for=condition=available deployment/auth-service-deployment --timeout=300s -n qbit
          echo "Core services deployed successfully!"