name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/dependabot.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: production
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build packages
        run: npm run build
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./services/api-gateway
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-api-gateway:latest
      
      - name: Build and push Auth Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-auth:latest
      
      - name: Build and push Web App
        uses: docker/build-push-action@v4
        with:
          context: ./apps/web
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/qbit-web:latest
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/api-gateway.yaml
          kubectl apply -f k8s/auth-service.yaml
          kubectl apply -f k8s/database.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/redis.yaml
          kubectl rollout restart deployment api-gateway-deployment auth-service-deployment web-deployment 